### ISSUE TITLE
CryFS 1.0.0 on Windows does not support "-f" param

### ISSUE THREAD

**Issue by lkankowski** [mhogomchungu/sirikali#281]
CryFS 1.0.0 on Windows does not support "-f" param, but running in foreground is now the only option.
Please remove hardcoded "-f".

**Comment by mhogomchungu** [comment]
Because of the option, CryFS is not running at all or it runs but complains about the option?

CryFS does not seem to want to run on my windows 10, i run it, i see a spinning ball for a few seconds and  then nothing.

**Comment by mhogomchungu** [comment]
Can you post the full output.

**Comment by lkankowski** [comment]
Sure, but I’ll only be able to use Windows in the evening.

**Comment by mhogomchungu** [comment]
Use below git builds and check if they solved the problem

https://github.com/mhogomchungu/sirikali/releases/tag/1.5.2

**Comment by lkankowski** [comment]
When checked with portable "SiriKaliQt6.git.zip" and "SiriKaliQt5.git.setup.exe" it works OK - creates and mount CryFS.
With "SiriKaliQt6.git.setup.exe" it doesn't work on my Windows 11 - crashes when trying to create or mount CryFS without any error. I think, that it may be a separate problem, not necessarily related to this issue.

Also looked into the code change (I am not C++ programmer) and I think that it may break compatibility with pre 1.0 version, so please keep that in mind ;)

**Comment by mhogomchungu** [comment]
You are correct about breaking compatibility with pre 1.0, fixed now.

Are you saying it crashes when using Sirikali from "SiriKaliQt6.git.setup.exe" and it does not crash when using SiriKali from "SiriKaliQt6.git.zip" under windows 11?

**Comment by lkankowski** [comment]
Yes and No :)
Checked on my laptop with windows 11 and "SiriKaliQt6.git.setup.exe" works!

Now, re-checked the newest version on my desktop and still crashes.
The only log data I've found after crash is this:
```xml
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" />
    <EventID>1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2024-11-16T09:51:12.1155062Z" />
    <EventRecordID>130363</EventRecordID>
    <Correlation />
    <Execution ProcessID="28476" ThreadID="28280" />
    <Channel>Application</Channel>
    <Computer>gabinet</Computer>
    <Security UserID="S-1-5-21-3472879248-3070434596-2202497406-1001" />
  </System>
  <EventData>
    <Data Name="AppName">sirikali.exe</Data>
    <Data Name="AppVersion">0.0.0.0</Data>
    <Data Name="AppTimeStamp">67382d48</Data>
    <Data Name="ModuleName">libstdc++-6.dll</Data>
    <Data Name="ModuleVersion">0.0.0.0</Data>
    <Data Name="ModuleTimeStamp">00000000</Data>
    <Data Name="ExceptionCode">c0000005</Data>
    <Data Name="FaultingOffset">000000000007bdc6</Data>
    <Data Name="ProcessId">0x779c</Data>
    <Data Name="ProcessCreationTime">0x1db380cf900014f</Data>
    <Data Name="AppPath">C:\Program Files (x86)\SiriKali\sirikali.exe</Data>
    <Data Name="ModulePath">C:\Program Files (x86)\SiriKali\libstdc++-6.dll</Data>
    <Data Name="IntegratorReportId">b05df34f-6d31-4539-86a9-be30bd652168</Data>
    <Data Name="PackageFullName">
    </Data>
    <Data Name="PackageRelativeAppId">
    </Data>
  </EventData>
</Event>
```

```xml
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows Error Reporting" Guid="{0ead09bd-2157-539a-8d6d-c87f95b64d70}" />
    <EventID>1001</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2024-11-16T09:51:14.5517485Z" />
    <EventRecordID>130364</EventRecordID>
    <Correlation />
    <Execution ProcessID="28476" ThreadID="28280" />
    <Channel>Application</Channel>
    <Computer>gabinet</Computer>
    <Security UserID="S-1-5-21-3472879248-3070434596-2202497406-1001" />
  </System>
  <EventData>
    <Data Name="Bucket">1206396303021264778</Data>
    <Data Name="BucketType">4</Data>
    <Data Name="EventName">APPCRASH</Data>
    <Data Name="Response">Niedostępny</Data>
    <Data Name="CabId">0</Data>
    <Data Name="P1">sirikali.exe</Data>
    <Data Name="P2">0.0.0.0</Data>
    <Data Name="P3">67382d48</Data>
    <Data Name="P4">libstdc++-6.dll</Data>
    <Data Name="P5">0.0.0.0</Data>
    <Data Name="P6">00000000</Data>
    <Data Name="P7">c0000005</Data>
    <Data Name="P8">000000000007bdc6</Data>
    <Data Name="P9">
    </Data>
    <Data Name="P10">
    </Data>
    <Data Name="AttachedFiles">
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.b47a4aaa-1fb1-450b-af8f-6c372acb37e3.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.247ac935-d256-4776-8afd-476c9d166f6a.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.3fbf9cf9-045f-4987-b49b-63e4f0849351.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.18733d18-0c7a-4291-af80-8cd4afda149d.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.f1f0c89a-2fb1-4b19-96db-3fd492e9c821.tmp.xml</Data>
    <Data Name="StorePath">\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_sirikali.exe_9bb01c4bc7233ad94fef33e4a6a882bebfe958ea_2a1c02f0_2238b114-ef3c-465e-b2da-86027e8410be</Data>
    <Data Name="AnalysisSymbol">
    </Data>
    <Data Name="Rechecking">0</Data>
    <Data Name="ReportId">b05df34f-6d31-4539-86a9-be30bd652168</Data>
    <Data Name="ReportStatus">268435456</Data>
    <Data Name="HashedBucket">dac7910bd7ac2b6430bdfb0bbbed4f8a</Data>
    <Data Name="CabGuid">0</Data>
  </EventData>
</Event>
```
The only file related to this crash I've found is: [Report.zip](https://github.com/user-attachments/files/17784220/Report.zip)

**Comment by mhogomchungu** [comment]
When you look inside the folder of a portable version, you will see a folder named "local". The only difference between a portable version and installed version is the presence or absence of this folder.

**Comment by mhogomchungu** [comment]
> Now, re-checked the newest version on my desktop and still crashes.

What do you mean by "newest version"? 
Only test the git versions from [here](https://github.com/mhogomchungu/sirikali/releases/tag/1.5.2)

Released version 1.7.1 is out of date now and should not be used while testing if things work or not.

**Comment by lkankowski** [comment]
Yes, I meant the git builds. 

As the main issue (cryfs -f)) is now solver and app works on qt6 on second Win 11, I think we can close this issue ;)

**Comment by mhogomchungu** [comment]
New version is out and it has a fix for the reported issue

https://github.com/mhogomchungu/sirikali/releases/tag/1.7.2
